# Generated by Django 4.2.6 on 2023-11-01 22:14

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=11, unique=True)),
                ('amount_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_show', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_min_desirable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', to='products.productdatageneral')),
            ],
        ),
    ]
