# Generated by Django 4.2.6 on 2023-11-03 14:49

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stockproduct_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='stock_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=11, unique=True),
        ),
    ]
