# Generated by Django 4.2.6 on 2023-11-01 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDataGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=11, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('number_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('provider', models.ManyToManyField(blank=True, related_name='provider', to='providers.providers')),
            ],
        ),
        migrations.CreateModel(
            name='ValuesPriceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('real_price_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, default=0.21, max_digits=10, null=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('price_wholesale', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('price_sale', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productdatageneral')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='productdatageneral',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='productdatageneral',
            name='user_create_price',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cost_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=11, unique=True)),
                ('amount_total_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productdatageneral')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_cost', models.CharField(max_length=100)),
                ('amounts_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('add_price', models.BooleanField(default=True)),
                ('id_product_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcost')),
            ],
        ),
    ]
