# Generated by Django 4.2.6 on 2023-10-26 16:56

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdatageneral',
            name='sub_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='products.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcost',
            name='product_cost_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='productdatageneral',
            name='product_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=11, unique=True),
        ),
    ]
