# Generated by Django 4.2.6 on 2023-11-03 12:28

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_article_productdatageneral_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcost',
            name='amount_total_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productcost',
            name='product_cost_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='productdatageneral',
            name='product_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=11, unique=True),
        ),
    ]
