# Generated by Django 4.2.6 on 2023-11-03 14:49

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main
import spectrum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcost_id_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', spectrum.fields.ColorField(default='#00000', verbose_name='color')),
            ],
        ),
        migrations.AlterField(
            model_name='productcost',
            name='product_cost_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='productdatageneral',
            name='product_id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='productdatageneral',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colormodel'),
        ),
    ]
